_BASE_: Fast-COCO-InstanceSegmentation.yaml
MODEL:
  WEIGHTS: "pretrained_models/R-18.pkl"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
  SEM_SEG_HEAD:
    NUM_CLASSES: 8
DATASETS:
  TRAIN: ("cityscapes_fine_instance_seg_train",)
  TEST: ("cityscapes_fine_instance_seg_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005     # Halved learning rate
  MAX_ITER: 18600      # Adjusted for ~50 epochs on Cityscapes with batch size 8
  STEPS: (16500, 17800) # Adjusted proportionally for the new MAX_ITER
INPUT:
  MIN_SIZE_TEST: 576
  MAX_SIZE_TEST: 777
OUTPUT_DIR: "output/fastinst_r18_cityscapes_ppm-fpn_bs8_lr0.00005_50ep_x1_576" # Updated output directory name